### ISSUE TITLE
Puma gem fails to install on ruby:2.6-slim

### ISSUE THREAD

**Issue by katherinelim** [katherinelim/simple-rest-api#12]
The Puma gem fails to install on ruby:2.6-slim. It installs successfully on ruby:2.6 but the image size is 906MB.

However it works in the dev environment, and the image size is 127MB.

```BASH
$ auto/build 
/Users/katherine.lim/github/simple-rest-api
Sending build context to Docker daemon  181.8kB
Step 1/13 : FROM ruby:2.6-slim
 ---> 05e2c7d06818
Step 2/13 : LABEL maintainer="https://github.com/katherinelim/simple-rest-api"
 ---> Running in ee35808d54a7
Removing intermediate container ee35808d54a7
 ---> 22bc8ea4612d
Step 3/13 : RUN mkdir -p /app
 ---> Running in ca90317bf69e
Removing intermediate container ca90317bf69e
 ---> bdc0932b52f2
Step 4/13 : ADD . /app
 ---> daffd3c5255e
Step 5/13 : WORKDIR /app
 ---> Running in 264b2ffadc51
Removing intermediate container 264b2ffadc51
 ---> 0f61cf6e1234
Step 6/13 : RUN bundle install --path /usr/local/bundle
 ---> Running in 094fb3a71e51
Fetching gem metadata from https://rubygems.org/........
Fetching rake 12.3.2
Installing rake 12.3.2
Fetching backports 3.12.0
Installing backports 3.12.0
Using bundler 1.17.2
Fetching coderay 1.1.2
Installing coderay 1.1.2
Fetching diff-lcs 1.3
Installing diff-lcs 1.3
Fetching method_source 0.9.2
Installing method_source 0.9.2
Fetching multi_json 1.13.1
Installing multi_json 1.13.1
Fetching mustermann 1.0.3
Installing mustermann 1.0.3
Fetching pry 0.12.2
Installing pry 0.12.2
Fetching puma 3.12.1
Installing puma 3.12.1 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/usr/local/bundle/ruby/2.6.0/gems/puma-3.12.1/ext/puma_http11
/usr/local/bin/ruby -I /usr/local/lib/ruby/2.6.0 -r
./siteconf20190331-6-x3t2r9.rb extconf.rb
checking for BIO_read() in -lcrypto... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/bin/$(RUBY_BASE_NAME)
	--with-puma_http11-dir
	--without-puma_http11-dir
	--with-puma_http11-include
	--without-puma_http11-include=${puma_http11-dir}/include
	--with-puma_http11-lib
	--without-puma_http11-lib=${puma_http11-dir}/lib
	--with-openssl-dir
	--without-openssl-dir
	--with-openssl-include
	--without-openssl-include=${openssl-dir}/include
	--with-openssl-lib
	--without-openssl-lib=${openssl-dir}/lib
	--with-cryptolib
	--without-cryptolib
/usr/local/lib/ruby/2.6.0/mkmf.rb:467:in `try_do': The compiler failed to
generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/local/lib/ruby/2.6.0/mkmf.rb:552:in `try_link0'
	from /usr/local/lib/ruby/2.6.0/mkmf.rb:570:in `try_link'
	from /usr/local/lib/ruby/2.6.0/mkmf.rb:782:in `try_func'
	from /usr/local/lib/ruby/2.6.0/mkmf.rb:1016:in `block in have_library'
	from /usr/local/lib/ruby/2.6.0/mkmf.rb:959:in `block in checking_for'
	from /usr/local/lib/ruby/2.6.0/mkmf.rb:361:in `block (2 levels) in postpone'
	from /usr/local/lib/ruby/2.6.0/mkmf.rb:331:in `open'
	from /usr/local/lib/ruby/2.6.0/mkmf.rb:361:in `block in postpone'
	from /usr/local/lib/ruby/2.6.0/mkmf.rb:331:in `open'
	from /usr/local/lib/ruby/2.6.0/mkmf.rb:357:in `postpone'
	from /usr/local/lib/ruby/2.6.0/mkmf.rb:958:in `checking_for'
	from /usr/local/lib/ruby/2.6.0/mkmf.rb:1011:in `have_library'
	from extconf.rb:8:in `block in <main>'
	from extconf.rb:8:in `each'
	from extconf.rb:8:in `find'
	from extconf.rb:8:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can
be found here:

/usr/local/bundle/ruby/2.6.0/extensions/x86_64-linux/2.6.0/puma-3.12.1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/bundle/ruby/2.6.0/gems/puma-3.12.1
for inspection.
Results logged to
/usr/local/bundle/ruby/2.6.0/extensions/x86_64-linux/2.6.0/puma-3.12.1/gem_make.out

An error occurred while installing puma (3.12.1), and Bundler cannot continue.
Make sure that `gem install puma -v '3.12.1' --source 'https://rubygems.org/'`
succeeds before bundling.

In Gemfile:
  puma
The command '/bin/sh -c bundle install --path /usr/local/bundle' returned a non-zero code: 5
```

**Comment by katherinelim** [comment]
While browsing http://carstenrn.com/devops/2016/11/12/dockerize-a-ruby-application.html
installing build-essential solves the issue. The resulting image size is 340MB.

Further work could involve investigating ruby -alpine as the Docker base image.

```Dockerfile
FROM ruby:2.6-slim
# Install build-essential for puma on -slim
RUN apt-get -qq update && \
    apt-get -qq -y install build-essential --fix-missing --no-install-recommends
```
